spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
